name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

#------------------ PACKAGES -------------------#

dependencies:
  flutter:
    sdk: flutter

# Utility Packages
  http: ^1.6.0
  intl: ^0.20.2
  logger: ^2.6.2
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.7
  smooth_page_indicator: ^2.0.1
  
  # Icons
  iconsax: ^0.0.8 # Note: This package is outdated; consider 'iconsax_flutter: ^1.0.1' or 'iconsax_plus: ^1.0.0' for active maintenance
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.7.3
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.1.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

  lottie: ^3.3.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  connectivity_plus: ^7.0.0



#------------------ ./ PACKAGES END -------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/logos/
   - assets/icons/
   - assets/images/on_boarding_images/
   - assets/images/banners/
   - assets/images/animations/
   - assets/icons/categories/

  fonts:
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-Light.ttf
         weight: 300
       - asset: assets/fonts/Poppins-Regular.ttf
         weight: 400
       - asset: assets/fonts/Poppins-Italic.ttf
         style: italic
       - asset: assets/fonts/Poppins-Medium.ttf
         weight: 500
       - asset: assets/fonts/Poppins-MediumItalic.ttf
         weight: 500
         style: italic
       - asset: assets/fonts/Poppins-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Poppins-Bold.ttf
         weight: 800
      
